import { useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { CalendarDays, CheckCircle2, Clock3, Plus, Search, ShieldAlert, UserCheck, UserX, X } from 'lucide-react'
import api, { errorMessage } from '../api'
import { useAuth } from '../AuthContext'
import { Badge, Card, Empty, ErrorState, Loading, PageTitle, Progress, StatCard, Toast } from '../components/UI'

const localDate=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
const localTime=()=>new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false})
function StaffAttendance(){
 const [summary,setSummary]=useState(null),[rows,setRows]=useState(null),[status,setStatus]=useState(''),[room,setRoom]=useState(''),[q,setQ]=useState(''),[date,setDate]=useState(localDate()),[error,setError]=useState('')
 const [markOpen,setMarkOpen]=useState(false),[studentQuery,setStudentQuery]=useState(''),[candidates,setCandidates]=useState([]),[selected,setSelected]=useState(null),[saving,setSaving]=useState(false),[toast,setToast]=useState(null)
 const [mark,setMark]=useState({attendance_date:localDate(),attendance_time:localTime(),status:'PRESENT'})
 const load=()=>Promise.all([api.get('/dashboard/summary'),api.get('/attendance/today',{params:{status:status||undefined,room:room||undefined,q:q||undefined,date,limit:100}})]).then(([s,r])=>{setSummary(s.data);setRows(r.data)}).catch(e=>setError(errorMessage(e)))
 useEffect(()=>{const timer=setTimeout(load,200);return()=>clearTimeout(timer)},[status,room,q,date])
 useEffect(()=>{if(!markOpen)return;const timer=setTimeout(()=>api.get('/warden/students',{params:{q:studentQuery||undefined,page_size:20}}).then(r=>setCandidates(r.data.items)).catch(e=>setToast({type:'error',title:'Could not load students',message:errorMessage(e)})),200);return()=>clearTimeout(timer)},[markOpen,studentQuery])
 const saveAttendance=async e=>{e.preventDefault();if(!selected)return;setSaving(true);try{await api.post('/attendance/mark',{student_id:selected.id,...mark});setToast({title:'Attendance saved',message:`${selected.name} marked ${mark.status.toLowerCase()}.`});setMarkOpen(false);setSelected(null);setStudentQuery('');setDate(mark.attendance_date);load()}catch(e){setToast({type:'error',title:'Could not save attendance',message:errorMessage(e)})}finally{setSaving(false)}}
 if(error&&!rows)return <ErrorState message={error} retry={load}/>;if(!rows)return <Loading/>
 return <><PageTitle eyebrow="ATTENDANCE REGISTER" title="Attendance" subtitle="Record and search attendance by student, room, status and date." actions={<button className="btn primary" onClick={()=>setMarkOpen(true)}><Plus/> Mark attendance</button>}/>
 <div className="stats-grid"><StatCard label="Present today" value={summary.present} hint={`${summary.attendance_percentage}% of residents`} icon={UserCheck} tone="mint"/><StatCard label="Absent" value={summary.absent} hint="Explicitly marked absent" icon={UserX} tone="red" delay={.03}/><StatCard label="Late entries" value={summary.late} hint="After closing time" icon={ShieldAlert} tone="amber" delay={.06}/><StatCard label="Awaiting record" value={summary.not_recorded} hint="No attendance today" icon={Clock3} tone="gray" delay={.09}/></div>
 <Card className="table-card"><div className="table-tools"><div className="search-box"><Search/><input placeholder="Search name, roll number or student ID" value={q} onChange={e=>setQ(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>PRESENT</option><option>LATE</option><option>ABSENT</option></select><div className="filter-field"><input type="number" min="0" max="430" placeholder="Room" value={room} onChange={e=>setRoom(e.target.value)}/></div><label className="date-button"><CalendarDays/><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div>{rows.length?<div className="data-table attendance-table"><div className="data-row data-head"><span>STUDENT</span><span>ROOM</span><span>ENTRY TIME</span><span>METHOD</span><span>STATUS</span></div>{rows.map(r=><div className="data-row" key={r.id}><span className="person-cell"><i>{r.name.split(' ').map(x=>x[0]).slice(0,2)}</i><b>{r.name}<small>{r.roll_no}</small></b></span><span>{r.room===null?'Unassigned':`Room ${r.room}`}</span><span><b>{r.time}</b><small>{new Date(`${r.date}T00:00:00`).toLocaleDateString('en-IN')}</small></span><span className="face-ok">{r.verification_method==='FACE'?'Face verified':r.verification_method}</span><span><Badge>{r.status}</Badge></span></div>)}</div>:<Empty title="No attendance records found" message="Use Mark Attendance or choose another date."/>}<div className="table-footer"><span>{rows.length} matching records</span><span>Saved attendance records</span></div></Card>
 <AnimatePresence>{markOpen&&<div className="modal-backdrop" onMouseDown={()=>setMarkOpen(false)}><motion.div initial={{opacity:0,scale:.97,y:10}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0}} className="modal attendance-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="card-eyebrow">ATTENDANCE ENTRY</span><h2>Mark attendance</h2><p>Saving again for the same date updates the existing record.</p></div><button onClick={()=>setMarkOpen(false)}><X/></button></div><form onSubmit={saveAttendance}><label>Find student<div className="input-wrap"><Search/><input placeholder="Name, roll number or student ID" value={studentQuery} onChange={e=>{setStudentQuery(e.target.value);setSelected(null)}}/></div></label><div className="student-picker">{candidates.length?candidates.map(s=><button type="button" className={selected?.id===s.id?'selected':''} key={s.id} onClick={()=>setSelected(s)}><span className="person-cell"><i>{s.name.split(' ').map(x=>x[0]).slice(0,2)}</i><b>{s.name}<small>{s.roll_no} · {s.room===null?'No room':`Room ${s.room}`}</small></b></span>{selected?.id===s.id&&<CheckCircle2/>}</button>):<Empty title="No students found" message="Add a student first or change the search."/>}</div><div className="form-grid attendance-fields"><label>Date<input type="date" required value={mark.attendance_date} onChange={e=>setMark({...mark,attendance_date:e.target.value})}/></label><label>Time<input type="time" required value={mark.attendance_time} onChange={e=>setMark({...mark,attendance_time:e.target.value})}/></label><label>Status<select value={mark.status} onChange={e=>setMark({...mark,status:e.target.value})}><option value="PRESENT">Present</option><option value="LATE">Late</option><option value="ABSENT">Absent</option></select></label></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setMarkOpen(false)}>Cancel</button><button className="btn primary" disabled={!selected||saving}>{saving?'Saving…':'Save attendance'}</button></div></form></motion.div></div>}</AnimatePresence><Toast toast={toast} onClose={()=>setToast(null)}/></>
}

function StudentAttendance(){
 const [data,setData]=useState(null),[error,setError]=useState('')
 const load=()=>api.get('/student/attendance').then(r=>setData(r.data)).catch(e=>setError(errorMessage(e)))
 useEffect(()=>{load()},[])
 const calendar=useMemo(()=>{if(!data)return null;const now=new Date(),year=now.getFullYear(),month=now.getMonth();const daysInMonth=new Date(year,month+1,0).getDate();const mondayOffset=(new Date(year,month,1).getDay()+6)%7;const map=new Map(data.history.map(x=>[x.date,x]));return{label:now.toLocaleDateString('en-IN',{month:'long',year:'numeric'}),blanks:mondayOffset,days:Array.from({length:daysInMonth},(_,i)=>{const d=i+1,key=`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;return{day:d,future:d>now.getDate(),...map.get(key)}})}} ,[data])
 if(error)return <ErrorState message={error} retry={load}/>;if(!data)return <Loading/>
 return <><PageTitle eyebrow="MY ATTENDANCE" title="Attendance" subtitle="Your saved hostel attendance history." actions={<button className="btn secondary" onClick={load}>Refresh</button>}/>
 <div className="student-attendance-top"><Card className="score-card"><div className="score-ring" style={{'--score':`${data.overall*3.6}deg`}}><div><strong>{data.overall}<sup>%</sup></strong><span>Overall</span></div></div><div><span className="card-eyebrow">RECORDED HISTORY</span><h2>{data.history.length?'Attendance summary':'No records yet'}</h2><p>{data.history.length?'Calculated from your saved attendance records.':'Ask the Warden or Administrator to mark attendance. Your records will then appear here.'}</p><Progress value={data.overall}/></div></Card><div className="mini-stats"><Card><i className="mint"><CheckCircle2/></i><span>Present<strong>{data.present}</strong></span></Card><Card><i className="amber"><Clock3/></i><span>Late<strong>{data.late}</strong></span></Card><Card><i className="red"><UserX/></i><span>Absent<strong>{data.absent}</strong></span></Card></div></div>
 <Card className="calendar-card"><div className="card-head"><div><span className="card-eyebrow">DAILY HISTORY</span><h3>{calendar.label}</h3></div><div className="calendar-legend"><span><i className="present"></i>Present</span><span><i className="late"></i>Late</span><span><i className="absent"></i>Absent</span></div></div><div className="calendar-week"><span>MON</span><span>TUE</span><span>WED</span><span>THU</span><span>FRI</span><span>SAT</span><span>SUN</span></div><div className="calendar-grid">{Array.from({length:calendar.blanks},(_,i)=><span className="blank" key={`blank-${i}`}></span>)}{calendar.days.map(d=><div key={d.day} className={d.status?.toLowerCase()||(d.future?'future':'')}><b>{d.day}</b>{d.status&&<><i></i><small>{d.time}</small></>}</div>)}</div></Card>
 <Card className="history-table"><div className="card-head"><div><span className="card-eyebrow">RECENT LOG</span><h3>Attendance history</h3></div></div>{data.history.length?data.history.slice(0,12).map(r=><div className="history-row" key={r.date}><span><CalendarDays/><b>{new Date(r.date+'T00:00:00').toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</b></span><span>{r.time}</span><Badge>{r.status}</Badge></div>):<Empty title="No attendance history" message="Attendance marked by your Warden or Administrator will appear here."/>}</Card></>
}
export default function Attendance(){const{user}=useAuth();return user.role==='STUDENT'?<StudentAttendance/>:<StaffAttendance/>}
