import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { BellRing, BookOpenText, CalendarDays, Clock3, DoorOpen, Megaphone, Phone, Plus, ShieldCheck, SunMedium, X } from 'lucide-react'
import api, { errorMessage } from '../api'
import { useAuth } from '../AuthContext'
import { Badge, Card, Empty, ErrorState, Loading, PageTitle, Toast } from '../components/UI'

export function Timings(){
 const[data,setData]=useState(null),[error,setError]=useState('');const load=()=>api.get('/hostel/timings').then(r=>setData(r.data)).catch(e=>setError(errorMessage(e)));useEffect(()=>{load()},[])
 if(error)return <ErrorState message={error} retry={load}/>;if(!data)return <Loading/>;const icons=[DoorOpen,DoorOpen,SunMedium,SunMedium,Clock3,Clock3,BookOpenText]
 return <><PageTitle eyebrow="DAILY SCHEDULE" title="Hostel timings" subtitle="Meal, study-hall and main-gate timings configured by the hostel."/><div className="timings-hero"><div><Clock3/><span>MAIN GATE CLOSES</span><strong>{data.find(x=>x.key==='gate_close')?.value}</strong><p>Entry after this time is recorded as late.</p></div><CalendarDays/></div><div className="timings-grid">{data.map((t,i)=>{const Icon=icons[i]||Clock3;return <Card key={t.id} delay={i*.04}><span><Icon/></span><small>{t.label.toUpperCase()}</small><strong>{t.value}</strong><p>{i<2?'Main entrance':i===6?'Study hall':'Main hostel mess'}</p></Card>})}</div></>
}

export function Wardens(){
 const[data,setData]=useState(null),[error,setError]=useState('');const load=()=>api.get('/wardens').then(r=>setData(r.data)).catch(e=>setError(errorMessage(e)));useEffect(()=>{load()},[])
 if(error)return <ErrorState message={error} retry={load}/>;if(!data)return <Loading/>
 return <><PageTitle eyebrow="HOSTEL CONTACTS" title="Wardens" subtitle="Authorised Warden contacts assigned to Malla Reddy Boys Hostel."/>{data.length?<><div className="directory-grid">{data.map((w,i)=><Card className="warden-card" key={`${w.name}-${w.phone}`} delay={i*.06}><div className="warden-photo">{w.name.split(' ').map(x=>x[0]).slice(0,2)}<i></i></div><Badge>ACTIVE</Badge><h2>{w.name}</h2><p>{w.designation}</p><div className="availability"><Clock3/><span>Availability<strong>{w.availability}</strong></span></div><a className="btn primary full" href={`tel:${w.phone}`}><Phone/> Call {w.name.split(' ')[0]}</a><small className="phone-number">{w.phone}</small></Card>)}</div><Card className="emergency-note"><ShieldCheck/><div><strong>Emergency?</strong><span>For immediate danger call India’s emergency number <b>112</b>, then notify a Warden.</span></div></Card></>:<Card><Empty title="No Warden contacts available" message="An Administrator must create an active Warden account."/></Card>}</>
}

export function Notices(){
 const{user}=useAuth();const[data,setData]=useState(null),[error,setError]=useState(''),[modal,setModal]=useState(false),[form,setForm]=useState({title:'',message:'',priority:'NORMAL',hostel_id:1}),[saving,setSaving]=useState(false),[toast,setToast]=useState(null)
 const canCreate=['ADMIN','WARDEN'].includes(user.role);const load=()=>api.get('/notices').then(r=>setData(r.data)).catch(e=>setError(errorMessage(e)));useEffect(()=>{load()},[])
 const publish=async e=>{e.preventDefault();setSaving(true);try{await api.post('/notices',form);setModal(false);setForm({title:'',message:'',priority:'NORMAL',hostel_id:1});setToast({title:'Notice published',message:'Students can see it immediately.'});load()}catch(e){setToast({type:'error',title:'Could not publish',message:errorMessage(e)})}finally{setSaving(false)}}
 if(error)return <ErrorState message={error} retry={load}/>;if(!data)return <Loading/>
 return <><PageTitle eyebrow="HOSTEL BULLETIN" title="Notices" subtitle="Official notices published by authorised hostel staff." actions={canCreate&&<button className="btn primary" onClick={()=>setModal(true)}><Plus/> New notice</button>}/><div className="notices-layout"><div className="notice-list">{data.length?data.map((n,i)=><Card className={`notice-card ${n.priority.toLowerCase()}`} key={n.id} delay={i*.04}><span className="notice-glyph">{n.priority==='IMPORTANT'?<Megaphone/>:<BellRing/>}</span><div><div className="notice-meta"><Badge>{n.priority}</Badge><span>{new Date(n.published_at).toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}</span></div><h2>{n.title}</h2><p>{n.message}</p></div></Card>):<Card><Empty title="No notices published" message={canCreate?'Use New Notice to publish the first hostel update.':'Hostel notices will appear here.'}/></Card>}</div><Card className="notice-side"><BookOpenText/><h3>Official bulletin</h3><p>Only authorised Admin and Warden accounts can publish information here.</p><div><span>{data.length}</span><small>ACTIVE NOTICES</small></div></Card></div><AnimatePresence>{modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><motion.div initial={{opacity:0,scale:.97}} animate={{opacity:1,scale:1}} className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="card-eyebrow">RESIDENT COMMUNICATION</span><h2>Publish notice</h2><p>Visible to students immediately.</p></div><button onClick={()=>setModal(false)}><X/></button></div><form onSubmit={publish}><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>NORMAL</option><option>IMPORTANT</option><option>URGENT</option></select></label><label>Message<textarea required rows="6" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setModal(false)}>Cancel</button><button className="btn primary" disabled={saving}>{saving?'Publishing…':'Publish now'}</button></div></form></motion.div></div>}</AnimatePresence><Toast toast={toast} onClose={()=>setToast(null)}/></>
}
