import { useEffect, useState } from 'react'
import { Archive, CheckCircle2, Download, FileSpreadsheet, FileText, LockKeyhole, ShieldCheck } from 'lucide-react'
import api, { errorMessage } from '../api'
import { Card, ErrorState, Loading, PageTitle, Toast } from '../components/UI'

export default function Reports(){
 const [filters,setFilters]=useState({room_from:0,room_to:430,status:'All',format:'zip'}),[preview,setPreview]=useState(null),[loading,setLoading]=useState(true),[downloading,setDownloading]=useState(false),[toast,setToast]=useState(null)
 const load=()=>{setLoading(true);api.get('/reports/rooms',{params:filters}).then(r=>setPreview(r.data)).catch(e=>setToast({type:'error',title:'Could not preview',message:errorMessage(e)})).finally(()=>setLoading(false))}
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[filters.room_from,filters.room_to,filters.status])
 const download=async()=>{setDownloading(true);try{const res=await api.get('/reports/rooms/download',{params:filters,responseType:'blob'});const url=URL.createObjectURL(res.data);const a=document.createElement('a');a.href=url;a.download=`Hostel_Room_Report.${filters.format}`;a.click();URL.revokeObjectURL(url);setToast({title:'Report generated',message:`Secure ${filters.format.toUpperCase()} download is ready.`})}catch(e){setToast({type:'error',title:'Download failed',message:errorMessage(e)})}finally{setDownloading(false)}}
 return <><PageTitle eyebrow="SECURE EXPORT CENTRE" title="Room reports" subtitle="Generate audit-tracked occupancy files without exposing data in the browser."/>
 <div className="report-layout"><Card className="report-builder"><div className="builder-head"><span><FileSpreadsheet/></span><div><h2>Room occupancy report</h2><p>Choose a range, occupancy state and file format.</p></div></div><div className="builder-section"><label>Room range</label><div className="range-fields"><div><span>FROM</span><input type="number" min="0" max="430" value={filters.room_from} onChange={e=>setFilters({...filters,room_from:+e.target.value})}/></div><i>→</i><div><span>TO</span><input type="number" min="0" max="430" value={filters.room_to} onChange={e=>setFilters({...filters,room_to:+e.target.value})}/></div></div><small>Valid hostel rooms: 0 through 430</small></div><div className="builder-section"><label>Occupancy status</label><div className="report-options">{['All','Occupied','Partially Occupied','Empty'].map(x=><button key={x} className={filters.status===x?'active':''} onClick={()=>setFilters({...filters,status:x})}><span>{filters.status===x&&<CheckCircle2/>}</span>{x}</button>)}</div></div><div className="builder-section"><label>Download format</label><div className="format-options"><button className={filters.format==='csv'?'active':''} onClick={()=>setFilters({...filters,format:'csv'})}><FileText/><div><strong>CSV</strong><small>Master list</small></div></button><button className={filters.format==='xlsx'?'active':''} onClick={()=>setFilters({...filters,format:'xlsx'})}><FileSpreadsheet/><div><strong>Excel</strong><small>Formatted workbook</small></div></button><button className={filters.format==='zip'?'active':''} onClick={()=>setFilters({...filters,format:'zip'})}><Archive/><div><strong>ZIP bundle</strong><small>Room files + master</small></div></button></div></div><button className="btn primary full report-download" onClick={download} disabled={downloading||filters.room_from>filters.room_to}><Download/>{downloading?'Generating securely…':'Generate & download report'}</button></Card>
 <div className="report-side"><Card className="report-preview"><div className="card-head"><div><span className="card-eyebrow">LIVE PREVIEW</span><h3>What’s included</h3></div><span className="live-indicator">LIVE</span></div>{loading?<Loading label="Calculating report…"/>:preview&&<><div className="report-big-stat"><strong>{preview.room_count}</strong><span>rooms selected<small>{preview.bed_count} bed records</small></span></div><div className="report-breakdown"><div><span>Occupied beds</span><strong>{preview.occupied}</strong></div><div><span>Vacant beds</span><strong>{preview.bed_count-preview.occupied}</strong></div><div><span>Room files</span><strong>{filters.format==='zip'?preview.room_count:1}</strong></div></div><div className="file-tree"><strong><Archive/> Hostel_Room_Report.zip</strong><span>├── Room_{String(filters.room_from).padStart(3,'0')}.csv</span><span>├── …</span><span>├── Room_{String(filters.room_to).padStart(3,'0')}.csv</span><span>└── Complete_Hostel_Room_List.xlsx</span></div></>}</Card><Card className="security-card"><span><ShieldCheck/></span><div><strong>Protected report delivery</strong><p>Only Admin and Warden roles can generate this report. This download will be recorded in the audit log.</p><small><LockKeyhole/> Server generated · No public URL</small></div></Card></div></div><Toast toast={toast} onClose={()=>setToast(null)}/></>
}