import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { BedDouble, Building2, ChevronLeft, ChevronRight, DoorOpen, Search, SlidersHorizontal, UserRound, X } from 'lucide-react'
import api, { errorMessage } from '../api'
import { Badge, Card, ErrorState, Loading, PageTitle, Progress } from '../components/UI'

export default function Rooms(){
 const [data,setData]=useState(null),[q,setQ]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[detail,setDetail]=useState(null),[error,setError]=useState('')
 const load=()=>api.get('/warden/rooms',{params:{q:q===''?undefined:q,status:status||undefined,page,page_size:24}}).then(r=>setData(r.data)).catch(e=>setError(errorMessage(e)))
 useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t)},[q,status,page])
 const open=async number=>{const {data}=await api.get(`/warden/rooms/${number}`);setDetail(data)}
 if(error&&!data)return <ErrorState message={error} retry={load}/>; if(!data)return <Loading/>
 const pages=Math.ceil(data.total/data.page_size)
 return <><PageTitle eyebrow="SPACE MANAGEMENT" title="Rooms & beds" subtitle="431 rooms · 1,724 beds · real-time vacancy control"/>
 <Card className="room-toolbar"><div className="search-box"><Search/><input type="number" min="0" max="430" placeholder="Find room 0–430" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></div><div className="segmented"><button className={!status?'active':''} onClick={()=>{setStatus('');setPage(1)}}>All rooms</button><button className={status==='FULL'?'active':''} onClick={()=>{setStatus('FULL');setPage(1)}}>Full</button><button className={status==='PARTIALLY_OCCUPIED'?'active':''} onClick={()=>{setStatus('PARTIALLY_OCCUPIED');setPage(1)}}>Available</button><button className={status==='EMPTY'?'active':''} onClick={()=>{setStatus('EMPTY');setPage(1)}}>Empty</button></div><span className="room-count">{data.total} rooms</span></Card>
 <div className="rooms-grid">{data.items.map((r,i)=><motion.button initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:(i%8)*.025}} className="room-card" key={r.id} onClick={()=>open(r.room_number)}><div className="room-card-head"><span><small>ROOM</small><strong>{String(r.room_number).padStart(3,'0')}</strong></span><Badge>{r.status}</Badge></div><div className="bed-visual">{[1,2,3,4].map(b=><div key={b} className={b<=r.occupied?'occupied':''}><BedDouble/><span>{b}</span></div>)}</div><Progress value={r.occupied*25} tone={r.occupied===4?'navy':'mint'}/><div className="room-card-foot"><span><b>{r.occupied}</b> occupied</span><span><b>{r.available}</b> available</span></div></motion.button>)}</div>
 <div className="pagination"><button disabled={page===1} onClick={()=>setPage(x=>x-1)}><ChevronLeft/> Previous</button><span>Page <b>{page}</b> of {pages}</span><button disabled={page===pages} onClick={()=>setPage(x=>x+1)}>Next <ChevronRight/></button></div>
 <AnimatePresence>{detail&&<div className="modal-backdrop" onMouseDown={()=>setDetail(null)}><motion.div initial={{opacity:0,scale:.96,y:15}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0}} className="modal room-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="card-eyebrow">BLOCK A · FLOOR {Math.floor(detail.room_number/100)+1}</span><h2>Room {String(detail.room_number).padStart(3,'0')}</h2><p>{detail.occupied} of 4 beds occupied</p></div><button onClick={()=>setDetail(null)}><X/></button></div><div className="room-summary-strip"><div><DoorOpen/><span><small>STATUS</small><Badge>{detail.status}</Badge></span></div><div><BedDouble/><span><small>AVAILABLE</small><strong>{detail.available} beds</strong></span></div><div><Building2/><span><small>CAPACITY</small><strong>4 residents</strong></span></div></div><div className="bed-list"><div className="bed-list-head"><span>BED</span><span>RESIDENT</span><span>ROLL NUMBER</span><span>STATUS</span></div>{detail.beds.map(b=><div className="bed-list-row" key={b.id}><span className="bed-number"><BedDouble/> {b.bed_number}</span>{b.student?<><span className="person-cell"><i>{b.student.name.split(' ').map(x=>x[0]).slice(0,2)}</i><b>{b.student.name}</b></span><span>{b.student.roll_no}</span><Badge>OCCUPIED</Badge></>:<><span className="vacant-person"><UserRound/> Vacant</span><span>—</span><Badge>VACANT</Badge></>}</div>)}</div><div className="modal-actions"><span className="modal-hint">Bed assignments are managed from the student profile.</span><button className="btn secondary" onClick={()=>setDetail(null)}>Close</button></div></motion.div></div>}</AnimatePresence></>
}