import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { BriefcaseBusiness, ChefHat, Mail, Phone, Plus, Search, ShieldCheck, X } from 'lucide-react'
import api, { errorMessage } from '../api'
import { Badge, Card, Empty, ErrorState, Loading, PageTitle, Toast } from '../components/UI'

const blank={name:'',email:'',phone:'',employee_id:'',designation:'',assigned_area:'',temporary_password:'',hostel_id:1}
export default function Staff({type}){const plural=type==='wardens'?'Wardens':'Cooks',Icon=type==='wardens'?ShieldCheck:ChefHat
 const[data,setData]=useState(null),[query,setQuery]=useState(''),[modal,setModal]=useState(false),[form,setForm]=useState(blank),[saving,setSaving]=useState(false),[toast,setToast]=useState(null),[error,setError]=useState('')
 const load=()=>api.get(`/admin/${type}`).then(r=>setData(r.data)).catch(e=>setError(errorMessage(e)));useEffect(()=>{load()},[type])
 const submit=async e=>{e.preventDefault();setSaving(true);try{await api.post(`/admin/${type}`,form);setToast({title:`${plural.slice(0,-1)} account created`,message:'The user must change this temporary password at first sign-in.'});setModal(false);setForm(blank);load()}catch(e){setToast({type:'error',title:'Could not create account',message:errorMessage(e)})}finally{setSaving(false)}}
 const setStatus=async staff=>{const next=staff.status==='ACTIVE'?'DISABLED':'ACTIVE';if(next==='DISABLED'&&!confirm(`Disable ${staff.name}'s account?`))return;try{await api.patch(`/admin/staff/${staff.id}`,{status:next});setToast({title:`Account ${next==='ACTIVE'?'enabled':'disabled'}`,message:`${staff.name}'s access has been updated.`});load()}catch(e){setToast({type:'error',title:'Could not update account',message:errorMessage(e)})}}
 if(error)return <ErrorState message={error} retry={load}/>;if(!data)return <Loading/>
 const filtered=data.filter(s=>`${s.name} ${s.email} ${s.employee_id||''}`.toLowerCase().includes(query.toLowerCase()))
 return <><PageTitle eyebrow="TEAM & ACCESS" title={plural} subtitle={type==='wardens'?'Create and manage authorised Warden accounts.':'Create and manage mess-only Cook accounts.'} actions={<button className="btn primary" onClick={()=>setModal(true)}><Plus/> Add {plural.slice(0,-1).toLowerCase()}</button>}/><div className="staff-summary"><Card><Icon/><div><span>Active {plural.toLowerCase()}</span><strong>{data.filter(x=>x.status==='ACTIVE').length}</strong></div></Card><Card><BriefcaseBusiness/><div><span>Total accounts</span><strong>{data.length}</strong></div></Card></div><Card className="table-card"><div className="table-tools"><div className="search-box"><Search/><input placeholder={`Search ${plural.toLowerCase()}`} value={query} onChange={e=>setQuery(e.target.value)}/></div></div>{filtered.length?<div className="data-table staff-table"><div className="data-row data-head"><span>TEAM MEMBER</span><span>EMPLOYEE ID</span><span>ASSIGNMENT</span><span>CONTACT</span><span>STATUS</span><span>ACTION</span></div>{filtered.map(s=><div className="data-row" key={s.id}><span className="person-cell"><i>{s.name.split(' ').map(x=>x[0]).slice(0,2)}</i><b>{s.name}<small>{s.role}</small></b></span><span>{s.employee_id||'—'}</span><span>{s.designation||'Main Hostel'}</span><span><small><Mail/> {s.email}</small><small><Phone/> {s.phone}</small></span><span><Badge>{s.status}</Badge></span><button className="table-action" onClick={()=>setStatus(s)}>{s.status==='ACTIVE'?'Disable':'Enable'}</button></div>)}</div>:<Empty title={query?'No matching accounts':`No ${plural.toLowerCase()} added`} message={query?'Try another search.':`Use Add ${plural.slice(0,-1)} to create the first account.`}/>}</Card>
 <AnimatePresence>{modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><motion.div initial={{opacity:0,scale:.97}} animate={{opacity:1,scale:1}} className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="card-eyebrow">ADMIN ONLY</span><h2>Create {plural.slice(0,-1).toLowerCase()}</h2><p>The user must change their temporary password at first sign-in.</p></div><button onClick={()=>setModal(false)}><X/></button></div><form onSubmit={submit}><div className="form-grid"><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Employee ID<input value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})}/></label><label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>{type==='wardens'?'Designation':'Assigned mess'}<input required value={type==='wardens'?form.designation:form.assigned_area} onChange={e=>setForm({...form,[type==='wardens'?'designation':'assigned_area']:e.target.value})}/></label><label>Temporary password<input type="password" required minLength="10" value={form.temporary_password} onChange={e=>setForm({...form,temporary_password:e.target.value})}/></label></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setModal(false)}>Cancel</button><button className="btn primary" disabled={saving}>{saving?'Creating…':`Create ${plural.slice(0,-1).toLowerCase()}`}</button></div></form></motion.div></div>}</AnimatePresence><Toast toast={toast} onClose={()=>setToast(null)}/></>}
